### ISSUE TITLE
The thing never hears me.

### ISSUE THREAD

**Issue by donovan-maker** [GeorgeMC2610/KTANE-Bot#1]
Im saying the proper words, but it never hears me. The main issue is Freak. When i say "Freak No", it says "Vowel No". I WANTED FREAK, NOT VOWEL. Please fix this, i love this game and i would love it if you fixed this because i never have anyone to play this with.

**Comment by GeorgeMC2610** [comment]
Sorry to hear that. Can you provide a video or literally anything? That would help a ton. I'll look into this, when I have time.

**Comment by donovan-maker** [comment]
So, I recorded it in OBS but the audio was not there, so... Welp, thanks for looking into it, while recording it though i got it to work, but still, it does not always work so if you could fix it that would be very much appreciated. Thanks George.

**Comment by GeorgeMC2610** [comment]
I could, potentially, change the word it hears to be something else than "Freak". But it seems a little odd that it misses it. 

There is not much else I can do other than that, because the voice recognition engine is the C# default. So my hands are tied. But I'll try anything that I can think of.

**Comment by donovan-maker** [comment]
Maybe change the word to just the letters FRK just like you did with CAR

**Comment by donovan-maker** [comment]
Ok, so, i went through the code and I found form1.cs In form1.cs it has all of the bomb-check things. I changed "Freak" to "Fake". But then I had to google how to compile it and when i did all it did was give me an error. I don't know how to write in cs, im a python person, so, if you could make an update for it that changes Freak to Fake that would be awesome, thank you George.

**Comment by GeorgeMC2610** [comment]
Make sure you edit it with MS Visual Studio Community (2019 and newer) or Jetbrains Rider. These two IDEs will automatically compile it and run the program altogether. 

I will make sure to apply the edits when I can and release the executable, so you can run it.

**Comment by donovan-maker** [comment]
Thank you so much George. Can't wait for the update. 😁

**Comment by donovan-maker** [comment]
Oh, I thought that maybe you could make this program but in python with TKinter maybe. I know python so if you made the script in that and then use a library that can convert a python script into an executable that would be cool. Then if there were still errors then i could just edit the source code. Thanks again George.

**Comment by GeorgeMC2610** [comment]
Okay, so just so you know, all voice recognition "grammars" are located in Grammar > DefuseGrammar.cs. In there, you can find how the entire bot is designed to hear you. In the method `_BombCheckGrammar()` (Lines 31 to 64) you can modify what the bot is designed to hear whenever you're initializing the bomb. Change whatever you want to. I'm going to deploy a new release today for you.

**Comment by GeorgeMC2610** [comment]
I'm going to go ahead and close this issue. I pushed the changes. I'm actually not going to release a new version, so make sure to download the source code (the executable is included which means that you don't have to compile it again). Re-open the issue if you have the same problems. Take care!
